OTUS C++ Professional 2023: NIPFilter::TAddresses Class Reference
NIPFilter::TAddresses Class Reference
#include <addresses.hpp>
Public Member Functions
TAddresses ()
TAddresses (std::istream &istream)
void Add (TAddress address)
void ReverseLexicographicSort ()
template<class TFilter >
TAddresses ApplyFilter (const TFilter &filter) const
bool operator== (const TAddresses &other) const
Private Member Functions
TAddress ParseLine (const std::string &in)
Private Attributes
std::vector< TAddress > items
Friends
std::ostream & operator<< (std::ostream &os, const TAddresses &addresses)
Detailed Description
Definition at line 12 of file addresses.hpp.
Constructor & Destructor Documentation
TAddresses() [1/2]
NIPFilter::TAddresses::TAddresses () inline
Definition at line 14 of file addresses.hpp.
 {};
TAddresses() [2/2]
NIPFilter::TAddresses::TAddresses (std::istream & istream)
Definition at line 4 of file addresses.cpp.
{
         std::string line;
         while (std::getline(istream, line)) {
             this->items.emplace_back(ParseLine(line));
         }
     }
References items, and ParseLine().
Member Function Documentation
Add()
void NIPFilter::TAddresses::Add (TAddress address)
Definition at line 15 of file addresses.cpp.
{
         this->items.emplace_back(std::move(address));
     }
References items.
Referenced by TEST().
ApplyFilter()
template<class TFilter > TAddresses NIPFilter::TAddresses::ApplyFilter (const TFilter & filter) const inline
Definition at line 22 of file addresses.hpp.
{
             TAddresses out;
             std::copy_if(this->items.cbegin(), this->items.cend(), std::back_inserter(out.items), filter);
             return out;
         }
References items.
operator==()
bool NIPFilter::TAddresses::operator== (const TAddresses & other) const
Definition at line 26 of file addresses.cpp.
{
         return this->items == other.items;
     }
References items.
ParseLine()
TAddress NIPFilter::TAddresses::ParseLine (const std::string & in) private
Definition at line 30 of file addresses.cpp.
{
         auto pos = in.find_first_of('\t');
         return TAddress(in.substr(0, pos));
     }
Referenced by TAddresses().
ReverseLexicographicSort()
void NIPFilter::TAddresses::ReverseLexicographicSort ()
Definition at line 11 of file addresses.cpp.
{
         std::sort(this->items.rbegin(), this->items.rend());
     }
References items.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const TAddresses & addresses) friend
Definition at line 19 of file addresses.cpp.
{
         for (const auto& address : addresses.items) {
             os << address << std::endl;
         }
         return os;
     }
Field Documentation
items
std::vector<TAddress> NIPFilter::TAddresses::items private
Definition at line 33 of file addresses.hpp.
Referenced by Add(), ApplyFilter(), operator==(), ReverseLexicographicSort(), and TAddresses().
The documentation for this class was generated from the following files:
02_ip_filter/addresses.hpp
02_ip_filter/addresses.cpp