OTUS C++ Professional 2023: NAllocator Namespace Reference
NAllocator Namespace Reference
Data Structures
struct deleter
struct THeapAllocator
class TContainer
Functions
template<class T , size_t TN, class U , size_t UN>
constexpr bool operator== (const THeapAllocator< T, TN > &lhs, const THeapAllocator< U, UN > &rhs) noexcept
template<class T , size_t TN, class U , size_t UN>
constexpr bool operator!= (const THeapAllocator< T, TN > &lhs, const THeapAllocator< U, UN > &rhs) noexcept
template<class T >
T Factorial (T n)
Function Documentation
Factorial()
template<class T > T NAllocator::Factorial (T n)
Definition at line 3 of file factorial.hpp.
                      {
         if (n == 0) {
             return 1;
         }
         return n * Factorial(n - 1);
     };
Referenced by fillMap(), fillVector(), and TEST().
operator!=()
template<class T , size_t TN, class U , size_t UN> constexpr bool NAllocator::operator!= (const THeapAllocator< T, TN > & lhs, const THeapAllocator< U, UN > & rhs) constexpr noexcept
Definition at line 85 of file allocator.hpp.
{
         return lhs.pools != rhs.pools;
     };
operator==()
template<class T , size_t TN, class U , size_t UN> constexpr bool NAllocator::operator== (const THeapAllocator< T, TN > & lhs, const THeapAllocator< U, UN > & rhs) constexpr noexcept
Definition at line 80 of file allocator.hpp.
{
         return lhs.pools == rhs.pools;
     }