# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get install \
          cmake clang libgtest-dev \
          libboost-filesystem-dev libboost-program-options-dev libboost-regex1.74-dev 
          libboost-system-dev libboost-log-dev libssl-dev libasio-dev

    - name: Build and test
      run: |
        mkdir ${{github.workspace}}/packages
        
        HOMEWORK_DIRS=$(find . -type d -regex '\.\/[0-9]+_.*' -maxdepth 1 | sort)
        echo $HOMEWORK_DIRS
        
        for HOMEWORK_DIR in $HOMEWORK_DIRS; do
            mkdir "${HOMEWORK_DIR}"/build

            pushd "${HOMEWORK_DIR}"/build

            cmake -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D BUILD_NUMBER=${{github.run_number}} ..
            cmake --build . --config ${{env.BUILD_TYPE}} 

            ctest -C ${{env.BUILD_TYPE}}
            cpack -G DEB

            cp *.deb ${{github.workspace}}/packages/

            popd
        done

        echo $(realpath ${{github.workspace}}/packages)
        ls -l ${{github.workspace}}/packages

    - name: Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files:
         |
          ${{github.workspace}}/packages/helloworld-0.0.${{github.run_number}}-Linux.deb
          ${{github.workspace}}/packages/ip_filter-0.0.${{github.run_number}}-Linux.deb
          ${{github.workspace}}/packages/allocator-0.0.${{github.run_number}}-Linux.deb
          ${{github.workspace}}/packages/print_ip-0.0.${{github.run_number}}-Linux.deb
          ${{github.workspace}}/packages/editor-0.0.${{github.run_number}}-Linux.deb
          ${{github.workspace}}/packages/matrix-0.0.${{github.run_number}}-Linux.deb
          ${{github.workspace}}/packages/bulk-0.0.${{github.run_number}}-Linux.deb
          ${{github.workspace}}/packages/bayan-0.0.${{github.run_number}}-Linux.deb
          ${{github.workspace}}/packages/async-0.0.${{github.run_number}}-Linux.deb
          ${{github.workspace}}/packages/bulk-server-0.0.${{github.run_number}}-Linux.deb
        token: ${{secrets.RELEASE_TOKEN}}
        tag_name: 0.0.${{github.run_number}}
