name: docs
on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Doxygen Action C++
            uses: mattnotmitt/doxygen-action@v1.3.1
            with:
              working-directory: '.'
              doxyfile-path: 'docs/Doxyfile'

          - name: Upload Output Directory
            uses: actions/upload-artifact@v2
            with:
              name: doc-files
              path: docs
              retention-days: 1

    copy:
        runs-on: ubuntu-latest
        needs: build

        steps:
          - uses: actions/checkout@v3
            with:
              ref: gh-pages

          - name: Download Output Directory
            uses: actions/download-artifact@v2
            with:
              name: doc-files
              path: docs

          - name: Move files
            run: |
                mv docs/out/html/* .
                rm -rf docs

          - name: Commit changes
            uses: EndBug/add-and-commit@v7
            with:
              author_name: Vitaly Isaev
              author_email: vitalyisaev2@gmail.com
              message: 'Update docs'
              branch: gh-pages
              add: '["*", ]'
